name: Build and Release FuiEditor

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: FuiEditor.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore $env:Solution_Name

    # Restore and build the application
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore

    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=Release

    # Create a zip file of the build artifacts
    - name: Archive build artifacts
      run: |
        New-Item -Path . -Name "output" -ItemType "directory" -Force
        Copy-Item -Path "path-to-your-build-output/*" -Destination "./output" -Recurse
        Compress-Archive -Path "./output/*" -DestinationPath "FuiEditor.zip"

    # Upload the build artifacts to GitHub
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: FuiEditor
        path: FuiEditor.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: FuiEditor
        path: ./build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/FuiEditor.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
